import{useEffect,useRef,useState}from'react';import{ExperienceShell,ResultCard}from'@eazo/ui';
type Summary={tick:number;cells:number[];gas:number;worldChecksum:string};
const initial:Summary={tick:0,cells:Array.from({length:36},()=>0),gas:0,worldChecksum:'00000000'};
export function App(){const workerRef=useRef<Worker|null>(null);const[summary,setSummary]=useState(initial);const[material,setMaterial]=useState<1|2>(1);const[complete,setComplete]=useState(false);
  useEffect(()=>{const worker=new Worker(new URL('./simulation.worker.ts',import.meta.url),{type:'module'});worker.onmessage=(event:MessageEvent<Summary>)=>{setSummary(event.data);if(event.data.gas>=3)setComplete(true)};workerRef.current=worker;worker.postMessage({type:'reset'});return()=>worker.terminate()},[]);
  const add=(index:number)=>workerRef.current?.postMessage({type:'step',commands:[{type:'add',material,x:index}]});const reset=()=>{setComplete(false);workerRef.current?.postMessage({type:'reset'})};
  return <ExperienceShell eyebrow="Deterministic Worker fixture" title="Make a fart. Learn why it happened." description="Drop two harmless fictional materials into a tiny deterministic universe. The Worker owns truth; the UI waits for its summary." accent="#8cff85" status={`Tick ${summary.tick}`}>
    {complete?<ResultCard title="Three units of glorious gas." kicker={`Replay checksum ${summary.worldChecksum}`} onAgain={reset}><p>Learning point: reactions can share ingredients while producing very different structures. This fixture is a game rule, not a real recipe.</p></ResultCard>:
    <section className="lab-layout"><div className="panel lab-controls"><fieldset><legend>Material</legend><label><input type="radio" checked={material===1} onChange={()=>setMaterial(1)}/> Blue drop</label><label><input type="radio" checked={material===2} onChange={()=>setMaterial(2)}/> Spark crumb</label></fieldset><button type="button" onClick={()=>workerRef.current?.postMessage({type:'step'})}>Run one tick</button><button type="button" onClick={reset}>Clear</button><dl><div><dt>Tick</dt><dd>{summary.tick}</dd></div><div><dt>Gas</dt><dd>{summary.gas}/3</dd></div><div><dt>Checksum</dt><dd>{summary.worldChecksum}</dd></div></dl></div><div className="panel"><div className="matter-grid" role="grid" aria-label="Six by six command grid">{summary.cells.map((cell,index)=><button type="button" role="gridcell" aria-label={`Cell ${index+1}, ${cell===1?'blue drop':cell===2?'spark crumb':'empty'}`} className={`cell m${cell}`} onClick={()=>add(index)} key={index}/>)}</div><p className="goal" aria-live="polite">Goal: make 3 gas · current {summary.gas}</p></div></section>}
  </ExperienceShell>}
